id: P004160
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:57:19.793759
source_metadata:
  id: bdr:W21999
  title: ཤེར་ཕྱིན་མངོན་རྟོགས་རྒྱན་རྩ་འགྲེལ
  author: ''
  volumes:
    a646780fb4324ee6a8b0bd5c71437b47:
      image_group_id: I5019
      title: ''
      volume_number: 1
      total_pages: 704
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
