id: I1EEA2027
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T08:37:24+00:00'
last_modified: '2022-06-07T20:41:57.548997+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21999
  title: ཤེར་ཕྱིན་མངོན་རྟོགས་རྒྱན་རྩ་འགྲེལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    474F:
      image_group_id: I5019
      title: ''
      total_pages: 704
      order: 1
      base_file: 474F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
